import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Roboto , Poppins } from 'next/font/google'
import Navbar from "./components/Navbar";
import { ShootingStars } from "./components/ui/shooting-stars";
import { StarsBackground } from "./components/ui/stars-background";
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable:"--font-roboto-sans"
})
const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable:"--font-poppins-sans"

})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${poppins.variable} antialiased`}

      >
        <ShootingStars/>
        <StarsBackground/>
        <Navbar/>
        {children}
        
      </body>
    </html>
  );
}
